version: "3.8"

services:
  deno:
    container_name: deno
    working_dir: "/home/app"
    volumes:
      - .:/home/app/
    image: denoland/deno:1.31.2
    tty: true
    stdin_open: true
    command: ["bash"]
